//order
export const input_visitDate = '[name="tanggal_lahir"]'
export const input_time = '#root-children > div > div:nth-child(3) > div.mb-4.col-md-12 > div > div > div.heading-ticket-divider.row > div.mb-4.col-sm-12.col-md-12 > div.mb-3 > div > label > span.ant-radio > input'
export const input_qty = '[name="qty"]'
export const add_qty = '#root-children > div > div:nth-child(3) > div.mb-4.col-md-12 > div > div > div:nth-child(2) > div > div > div > div.d-flex.flex-column.gap-3 > div > button:nth-child(3)'
export const button_pesanSekarang = '#root-children > div > div:nth-child(3) > div.mb-4.col-md-12 > div > div > div:nth-child(3) > div > div > div:nth-child(2) > button'
//input form
export const input_firstName = '[data-test="firstname"]'
export const input_email = '[name="email"]'
export const input_emailConfirm = '[name="confirm_email"]'
export const input_phoneNumber = '[data-test="phone"]'
export const input_gender = '#rc_select_1'
export const input_genderMale = '[title="Male"]'
export const input_genderFemale = '[title="Female"]'
export const input_province = '#rc_select_2'
export const input_birthdate = '#form-lengkapi-data > div.modal-body > div:nth-child(7) > div > div > input'
export const input_ktp = '[name="id_number"]'
export const tnc = '.ant-checkbox-input'
export const modal_confirm = '.modal-footer > .btn-primary-v4'
export const button_pesanSekarangForm = '.justify-content-between > .btn-primary-v4'
//payment
export const cc = '#btn_11195ccb-787f-4b56-a9b9-d2d8c144cb3a'
export const cc_name = '#name'
export const cc_number = '#no_cc'
export const cc_month = '#ccmonth'
export const cc_year = '#ccyear'
export const cc_cvv = '#cvv'
export const cc_paybtn = '#btn-pay-cc'

